spring:
  application:
    name: spring-boot-mvc
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1

terminus:
  name: amazing

management:
  security:
    enabled: false